'use strict';
const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const {URL}=require('url');
const PORT=Number(process.env.PORT||4311),ROOT=__dirname,DATA=path.join(ROOT,'data'),DIR=path.join(DATA,'configs'),EVENTS=path.join(DATA,'events.jsonl'),PUBLIC=path.join(ROOT,'public');
const REVIEW=process.env.VOICE_CONFIG_REVIEW_MODE!=='0'; fs.mkdirSync(DIR,{recursive:true});
const offers={demo_activation:{code:'voice_demo_activation_v1',amount:20,label:'Activate Demo',next:'DEMO_PAID'},go_live:{code:'voice_go_live_v1',amount:49,label:'Go Live',next:'GO_LIVE_PAID'},managed_setup:{code:'voice_managed_setup_v1',amount:500,label:'Managed Implementation Setup',next:'MANAGED_SETUP_PAID'}};
const now=()=>new Date().toISOString(); const sha=s=>crypto.createHash('sha256').update(String(s)).digest('hex'); const tok=()=>crypto.randomBytes(24).toString('hex'); const id=()=>`VA-${crypto.randomBytes(5).toString('hex').toUpperCase()}`;
function send(res,n,obj,h={}){const body=typeof obj==='string'?obj:JSON.stringify(obj,null,2);res.writeHead(n,{'Content-Type':typeof obj==='string'?'text/plain; charset=utf-8':'application/json; charset=utf-8','Cache-Control':'no-store',...h});res.end(body)}
function body(req){return new Promise((ok,bad)=>{let s='';req.on('data',d=>{s+=d;if(s.length>200000)req.destroy()});req.on('end',()=>{try{ok(s?JSON.parse(s):{})}catch(e){bad(new Error('Invalid JSON'))}});req.on('error',bad)})}
function fp(i){if(!/^VA-[A-F0-9]{10}$/.test(i))throw new Error('Invalid config_id');return path.join(DIR,i+'.json')}
function load(i){const p=fp(i);return fs.existsSync(p)?JSON.parse(fs.readFileSync(p,'utf8')):null} function save(c){fs.writeFileSync(fp(c.config_id),JSON.stringify(c,null,2));return c}
function event(type,c,extra={}){fs.appendFileSync(EVENTS,JSON.stringify({at:now(),type,config_id:c?.config_id||null,version:c?.version||null,...extra})+'\n')}
function uniq(v){return Array.isArray(v)?[...new Set(v.map(x=>String(x).trim()).filter(Boolean))]:[]}
function canonical(c){return JSON.stringify({schema:c.schema,config_id:c.config_id,version:c.version,customer:{name:c.customer.name,email:c.customer.email},agent:c.agent,business:c.business,objectives:c.objectives,collect:c.collect,escalation:c.escalation,integrations_requested:c.integrations_requested,managed_features:c.managed_features,commercial:{selected_path:c.commercial.selected_path,plan:c.commercial.plan}})}
function rehash(c){c.config_hash='sha256:'+sha(canonical(c));return c} function auth(req,c){const h=String(req.headers.authorization||''),raw=h.startsWith('Bearer ')?h.slice(7):'';return !!raw&&sha(raw)===c.manage_token_hash}
function pub(c){const x=JSON.parse(JSON.stringify(c));delete x.manage_token_hash;delete x.verification_token_hash;delete x.verification_expires_at;return x}
function patch(c,b){c.customer.name=String(b.customer?.name??c.customer.name??'').trim().slice(0,120);c.customer.email=String(b.customer?.email??c.customer.email??'').trim().toLowerCase().slice(0,180);c.agent.name=String(b.agent?.name??c.agent.name??'Ashley').trim().slice(0,80)||'Ashley';c.agent.role=String(b.agent?.role??c.agent.role??'AI Receptionist').trim().slice(0,100)||'AI Receptionist';c.agent.direction=uniq(b.agent?.direction??c.agent.direction);c.agent.tone=String(b.agent?.tone??c.agent.tone??'friendly-professional').trim().slice(0,80);c.business.name=String(b.business?.name??c.business.name??'').trim().slice(0,140);c.business.hours=String(b.business?.hours??c.business.hours??'').trim().slice(0,240);c.business.services=uniq(b.business?.services??c.business.services).slice(0,25);c.objectives=uniq(b.objectives??c.objectives).slice(0,25);c.collect=uniq(b.collect??c.collect).slice(0,25);c.escalation={human_transfer:!!(b.escalation?.human_transfer??c.escalation.human_transfer),urgent_calls:!!(b.escalation?.urgent_calls??c.escalation.urgent_calls),destination:String(b.escalation?.destination??c.escalation.destination??'').trim().slice(0,160)};c.integrations_requested=uniq(b.integrations_requested??c.integrations_requested).slice(0,25);c.managed_features=uniq(b.managed_features??c.managed_features).slice(0,25);c.commercial.selected_path=String(b.commercial?.selected_path??c.commercial.selected_path??'').slice(0,80);c.commercial.plan=String(b.commercial?.plan??c.commercial.plan??'basic_receptionist').slice(0,80);c.updated_at=now();return rehash(c)}
function fresh(b={}){const mt=tok(),c={schema:'hdp.voice-agent-spec/v1',config_id:id(),config_hash:'',version:1,status:'DRAFT',created_at:now(),updated_at:now(),customer:{name:'',email:'',email_verified:false,verified_at:null},agent:{name:'Ashley',role:'AI Receptionist',direction:['inbound'],tone:'friendly-professional'},business:{name:'',hours:'',services:[]},objectives:['answer inbound calls','capture leads'],collect:['name','phone','reason_for_call'],escalation:{human_transfer:true,urgent_calls:true,destination:''},integrations_requested:[],managed_features:[],commercial:{selected_path:'',plan:'basic_receptionist',checkout_intents:[],payments:[]},lifecycle:[{at:now(),status:'DRAFT'}],manage_token_hash:sha(mt)};patch(c,b);save(c);event('config_created',c);return{c,mt}}
function status(c,s,d=''){if(c.status!==s){c.status=s;c.lifecycle.push({at:now(),status:s,detail:d});c.updated_at=now();save(c);event('status_changed',c,{status:s,detail:d})}}
function emailOk(x){return /^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(String(x||''))}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(req.method==='GET'&&u.pathname==='/health')return send(res,200,{ok:true,product:'HDP Voice Configurator',version:'1.0.0',review_mode:REVIEW,payment_live:false,email_live:false,provisioning_live:false});if(req.method==='GET'&&u.pathname==='/api/offers')return send(res,200,{offers,review_mode:REVIEW});if(req.method==='POST'&&u.pathname==='/api/configs'){const r=fresh(await body(req));return send(res,201,{config:pub(r.c),manage_token:r.mt})}
let m=u.pathname.match(/^\/api\/configs\/(VA-[A-F0-9]{10})$/);if(m&&req.method==='GET'){const c=load(m[1]);if(!c)return send(res,404,{error:'Not found'});if(!auth(req,c))return send(res,401,{error:'Manage token required'});return send(res,200,{config:pub(c)})}if(m&&req.method==='PATCH'){const c=load(m[1]);if(!c)return send(res,404,{error:'Not found'});if(!auth(req,c))return send(res,401,{error:'Manage token required'});c.version++;patch(c,await body(req));if(c.customer.email_verified){c.customer.email_verified=false;c.customer.verified_at=null;status(c,'CONFIGURED','Configuration changed; email verification must be reconfirmed.')}save(c);event('config_updated',c);return send(res,200,{config:pub(c)})}
m=u.pathname.match(/^\/api\/configs\/(VA-[A-F0-9]{10})\/request-verification$/);if(m&&req.method==='POST'){const c=load(m[1]);if(!c)return send(res,404,{error:'Not found'});if(!auth(req,c))return send(res,401,{error:'Manage token required'});if(!c.customer.name||!emailOk(c.customer.email))return send(res,400,{error:'A name and working-format email are required.'});const vt=tok();c.verification_token_hash=sha(vt);c.verification_expires_at=new Date(Date.now()+1800000).toISOString();c.customer.email_verified=false;c.customer.verified_at=null;status(c,'EMAIL_PENDING','Verification requested.');save(c);event('verification_requested',c);const out={ok:true,status:c.status,email:c.customer.email,delivery_mode:REVIEW?'REVIEW_LINK_ONLY':'EMAIL_ADAPTER_HOLD'};if(REVIEW)out.review_verification_token=vt;return send(res,200,out)}
if(req.method==='POST'&&u.pathname==='/api/verify'){const b=await body(req),c=load(String(b.config_id||''));if(!c)return send(res,404,{error:'Not found'});if(!c.verification_token_hash||sha(String(b.token||''))!==c.verification_token_hash)return send(res,400,{error:'Invalid verification token'});if(Date.parse(c.verification_expires_at)<Date.now())return send(res,400,{error:'Verification token expired'});c.customer.email_verified=true;c.customer.verified_at=now();delete c.verification_token_hash;delete c.verification_expires_at;status(c,'EMAIL_VERIFIED','Email verified.');save(c);event('email_verified',c);return send(res,200,{ok:true,config:pub(c)})}
m=u.pathname.match(/^\/api\/configs\/(VA-[A-F0-9]{10})\/checkout-intent$/);if(m&&req.method==='POST'){const c=load(m[1]);if(!c)return send(res,404,{error:'Not found'});if(!auth(req,c))return send(res,401,{error:'Manage token required'});if(!c.customer.email_verified)return send(res,409,{error:'Verify email before checkout.'});const b=await body(req),offer=offers[String(b.offer||'')];if(!offer)return send(res,400,{error:'Unknown offer'});const intent={intent_id:'VCI-'+crypto.randomBytes(6).toString('hex').toUpperCase(),created_at:now(),offer:offer.code,amount_usd:offer.amount,config_id:c.config_id,config_hash:c.config_hash,config_version:c.version,status:'CHECKOUT_PREPARED_HOLD'};c.commercial.selected_path=String(b.offer);c.commercial.checkout_intents.push(intent);status(c,'CHECKOUT_STARTED',offer.code);save(c);event('checkout_prepared',c,{intent_id:intent.intent_id,offer:intent.offer,amount_usd:intent.amount_usd});return send(res,200,{ok:true,intent,payment_live:false,checkout_url:null,message:'Checkout adapter is intentionally on HOLD in review mode.'})}
if(req.method==='GET'){let p=u.pathname==='/'?'/index.html':u.pathname;p=path.normalize(p).replace(/^(\.\.[\/\\])+/, '');const f=path.join(PUBLIC,p);if(f.startsWith(PUBLIC)&&fs.existsSync(f)&&fs.statSync(f).isFile()){const ext=path.extname(f).toLowerCase(),ct=ext==='.html'?'text/html; charset=utf-8':ext==='.js'?'application/javascript; charset=utf-8':ext==='.css'?'text/css; charset=utf-8':'application/octet-stream';res.writeHead(200,{'Content-Type':ct,'Cache-Control':'no-store','X-Robots-Tag':'noindex, nofollow, noarchive'});return fs.createReadStream(f).pipe(res)}}return send(res,404,{error:'Not found'})}catch(e){return send(res,500,{error:e.message})}});server.listen(PORT,'127.0.0.1',()=>console.log(`HDP Voice Configurator v1 listening on 127.0.0.1:${PORT}`));
